### ISSUE TITLE
gameFrame description

### ISSUE THREAD

**Issue by pbateman828** [CarolinaIgnites/gameFrame#12]
Could the description of gameFrame be updated, so that a person viewing gameFrame from a contributors profile be able to interpret it's meaning?

![screenshot from 2018-02-14 10-29-57](https://user-images.githubusercontent.com/17086606/36212758-d45a6a44-1172-11e8-9ad0-33d03ea92629.png)

**Comment by dmadisetti** [comment]
Yeah no prob. You don't have permissions?

**Comment by dmadisetti** [comment]
Gave you admin rights
